name: Auto Update Catalog

on:
  push:
    paths:
      - "images/**"

permissions:
  contents: write   # 👈 allow workflow to push commits

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # 👈 use GitHub’s built-in token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run changeNames.py
        run: python changeNames.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto: updated product catalog" || echo "No changes"
          git push
